dependencies:
- name: exposecontroller
  version: 2.3.58
  repository: http://chartmuseum.build.cd.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.58
  repository: http://chartmuseum.build.cd.jenkins-x.io
  alias: cleanup
- name: rabbitmq
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 0.8.0
- name: postgresql
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 0.11.0
